from enum import Enum


class RelationshipType(Enum):
    CONTAINS = "CONTAINS"
    IMPORTS = "IMPORTS"
    CALLS = "CALLS"
    INHERITS = "INHERITS"
    FUNCTION_DEFINITION = "FUNCTION_DEFINITION"
    CLASS_DEFINITION = "CLASS_DEFINITION"
    INSTANTIATES = "INSTANTIATES"
    TYPING = "TYPING"
    ASSIGNMENT = "ASSIGNMENT"
    USES = "USES"
